# Makefile для запуска тестов

# Имя Python-интерпретатора
PYTHON = python3

TEST_COMMAND = $(PYTHON)

test_custom_meta:
	$(TEST_COMMAND) custom_meta_test.py

test_descriptors:
	$(TEST_COMMAND) descriptors_test.py


tests: test_custom_meta test_descriptors